[package]

name = "SciRust"
version = "0.2.0"
authors = [ "Eric Holk <eholk@cs.indiana.edu>" ]
readme = "README.md"
tags = ["matrix", "numerical", "algorithms"]

[[lib]]

name = "scirust" 
path = "src/SciRust/lib.rs"

# vi: ft=conf
